In [11]:
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.preprocessing import LabelEncoder


In [12]:
d=pd.read_csv("Used_Bikes.csv")
d.head()

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [13]:
X=d.drop('price',axis=1)
y=d.price

In [14]:
le=LabelEncoder()

In [15]:
dfle=d

dfle.owner=le.fit_transform(dfle.owner)
dfle.brand=le.fit_transform(dfle.brand)
dfle

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

       owner   age  power  brand  
0          0   3.0  110.0     19  
1          0   4.0  350.0     17  
2          0   8.0  675.0     20  
3          0   4.0  180.0     19  
4          0   3.0  150.0     21  
...      ...   ...    ...    ...  
32643      0   4.0  100.0      5  
32644      0   9.0  180.0     19  
32645      0   6.0  220.0      1  
32646      0  16.0  125.0      5  
32647      0  13.0  150.0      1  

[32648 rows x 8 columns]

In [16]:
X = dfle[['age','kms_driven','owner', 'age', 'power', 'brand' ]]
y=dfle.price

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) 
X_test = scaler.transform(X_test)

In [29]:
X_train

array([[ 1.742121  ,  1.73500717, -0.29434983,  1.742121  , -0.47129391,
        -0.96728771],
       [ 1.49213393,  0.3879691 , -0.29434983,  1.49213393, -0.47129391,
        -0.44734355],
       [-0.00778851,  0.70111154, -0.29434983, -0.00778851, -0.10052683,
        -0.96728771],
       ...,
       [-0.75774973, -0.41916667, -0.29434983, -0.75774973, -0.39714049,
        -0.31735751],
       [-0.50776265, -0.28440446, -0.29434983, -0.50776265, -0.84206098,
        -0.96728771],
       [ 0.74217271, -0.27339888,  3.28944163,  0.74217271,  0.04778001,
        -0.96728771]])

In [30]:
X_test

array([[-0.00778851, -0.15754831, -0.29434983, -0.00778851, -0.84206098,
        -0.44734355],
       [-0.00778851,  0.74145036, -0.29434983, -0.00778851, -0.47129391,
        -0.31735751],
       [ 1.742121  ,  1.73500717, -0.29434983,  1.742121  , -0.47129391,
        -0.96728771],
       ...,
       [-0.50776265, -0.26764903, -0.29434983, -0.50776265,  0.04778001,
        -0.96728771],
       [ 1.99210807, -1.00902083, -0.29434983,  1.99210807, -0.84206098,
        -0.44734355],
       [-0.50776265, -0.64377034, -0.29434983, -0.50776265, -0.84206098,
        -0.44734355]])

In [20]:
model=LinearRegression()
model

LinearRegression()

In [21]:
carmode=model.fit(X_train,y_train)
carmode

LinearRegression()

In [22]:
carpred=carmode.predict(X_test)
carpred

array([ 9047.86726297, 31374.01495313, 15453.24610654, ...,
       82554.99759571,  -622.13273703, 15473.86726297])

In [23]:
score=r2_score(carpred,y_test)
score

0.6624218060602121

In [24]:
carmode.get_params().keys()

dict_keys(['copy_X', 'fit_intercept', 'n_jobs', 'normalize', 'positive'])

In [25]:
parameters={'copy_X':[1,2,5,10,20,30,40,50,60,70,80,90]}
linearcv=GridSearchCV(model,parameters,scoring='neg_mean_squared_error',cv=5)

In [26]:
linearcv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LinearRegression(),
             param_grid={'copy_X': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80,
                                    90]},
             scoring='neg_mean_squared_error')

In [27]:
linear_pred=linearcv.predict(X_test)
linear_pred

array([ 9047.86726297, 31374.01495313, 15453.24610654, ...,
       82554.99759571,  -622.13273703, 15473.86726297])

In [28]:
LinearScore=r2_score(linear_pred,y_test)
LinearScore

0.6624218060602121